### ISSUE TITLE
[Bug] Review MatrixBlock

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/qadence#9]
In a recent MR some issues were found in `MatrixBlock` and `block_to_tensor`. Few things to check:

- `MatrixBlock` allows any size matrix (e.g., 3x3), but `qubit_support` must be given, meaning the size should only be a power of 2.
- In `block_to_tensor` on a `MatrixBlock` the identity filling was not being done properly, currently disabled it just returns the matrix that was used to build the `MatrixBlock`.

**Comment by EthanObadia** [comment]
I found this bug using the code bellow on `main`:
```python3
import torch
import qadence 
from qadence.blocks.matrix import MatrixBlock

XMAT = torch.tensor([[0, 1], [1, 0]], dtype=torch.cdouble)
matblock = MatrixBlock(XMAT, (0,))
print(qadence.run(matblock))
```
Returns:
```zsh
Traceback (most recent call last):
  File "qadence/test.py", line 82, in <module>
    print(qadence.run(matblock))
          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qadence/execution.py", line 101, in _
    return run(Register(n_qubits), block, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "qadence/register.py", line 73, in __init__
    self.graph = support if isinstance(support, nx.Graph) else alltoall_graph(support)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "qadence/register.py", line 379, in alltoall_graph
    graph = nx.complete_graph(n_qubits)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 3, in argmap_complete_graph_1
  File "Qadence_venv/lib/python3.11/site-packages/networkx/utils/backends.py", line 633, in __call__
    return self.orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 8", line 3, in argmap_complete_graph_5
  File "Qadence_venv/lib/python3.11/site-packages/networkx/utils/decorators.py", line 255, in _nodes_or_number
    nodes = tuple(n)
            ^^^^^^^^

TypeError: 'numpy.float64' object is not iterable
```

@Roland-djee , @jpmoutinho.

**Comment by jpmoutinho** [comment]
Thanks @EthanObadia. Do you need `MatrixBlock`? This is another pandora's box to be opened...

**Comment by rajaiitp** [comment]
This is to declare any random matrix as a unitary operator I presume, I think I would need this. 
Isnt the output from an Hamevol for a general hamiltonian a matrixblock ?
